alias: HVAC limit enforcement
description: Restrict max temp for heat and min temp for cool
trigger:
  - platform: state
    entity_id:
      - climate.hvac_floor_0
      - climate.hvac_floor_1
      - climate.hvac_floor_2
    attribute: temperature
    for:
      hours: 0
      minutes: 0
      seconds: 0
condition: []
action:
  - alias: Variables
    variables:
      max_heat_setpoint: 21.67
      min_cool_setpoint: 19.44
      reference_entity_id: "{{ trigger.entity_id }}"
      target_setpoint: "{{ trigger.to_state.attributes.temperature }}"
  - alias: Call HVAC temperature enforcement script based on which thermostat called and on which setting (cool or heat)
    choose:
      - alias: Floor 0 thermostat called (heat)
        conditions:
          - alias: If changed thermostat is Floor 0
            condition: template
            value_template: "{{ reference_entity_id == 'climate.hvac_floor_0' }}"
          - alias: And heat setpoint is too high
            condition: template
            value_template: "{{ target_setpoint > max_heat_setpoint }}"
          - condition: state
            entity_id: climate.hvac_floor_0
            state: heat
        sequence:
          - service: climate.set_temperature
            metadata: {}
            data:
              temperature: 21.67
            target:
              entity_id: climate.hvac_floor_0
      - alias: Floor 0 thermostat called (cool)
        conditions:
          - alias: If changed thermostat is Floor 0
            condition: template
            value_template: "{{ reference_entity_id == 'climate.hvac_floor_0' }}"
          - alias: And heat setpoint is too high
            condition: template
            value_template: "{{ target_setpoint < min_cool_setpoint }}"
          - condition: state
            entity_id: climate.hvac_floor_0
            state: cool
        sequence:
          - service: climate.set_temperature
            metadata: {}
            data:
              temperature: 19.44
            target:
              entity_id: climate.hvac_floor_0
      - alias: Floor 1 thermostat called (heat)
        conditions:
          - alias: If changed thermostat is Floor 1
            condition: template
            value_template: "{{ reference_entity_id == 'climate.hvac_floor_1' }}"
          - alias: And heat setpoint is too high
            condition: template
            value_template: "{{ target_setpoint > max_heat_setpoint }}"
          - condition: state
            entity_id: climate.hvac_floor_1
            state: heat
        sequence:
          - service: climate.set_temperature
            metadata: {}
            data:
              temperature: 21.67
            target:
              entity_id: climate.hvac_floor_1
      - alias: Floor 1 thermostat called (cool)
        conditions:
          - alias: If changed thermostat is Floor 1
            condition: template
            value_template: "{{ reference_entity_id == 'climate.hvac_floor_1' }}"
          - alias: And heat setpoint is too high
            condition: template
            value_template: "{{ target_setpoint < min_cool_setpoint }}"
          - condition: state
            entity_id: climate.hvac_floor_1
            state: cool
        sequence:
          - service: climate.set_temperature
            metadata: {}
            data:
              temperature: 19.44
            target:
              entity_id: climate.hvac_floor_1
      - alias: Floor 2 thermostat called (heat)
        conditions:
          - alias: If changed thermostat is Floor 2
            condition: template
            value_template: "{{ reference_entity_id == 'climate.hvac_floor_2' }}"
          - alias: And heat setpoint is too high
            condition: template
            value_template: "{{ target_setpoint > max_heat_setpoint }}"
          - condition: state
            entity_id: climate.hvac_floor_2
            state: heat
        sequence:
          - service: climate.set_temperature
            metadata: {}
            data:
              temperature: 21.67
            target:
              entity_id: climate.hvac_floor_2
      - alias: Floor 2 thermostat called (cool)
        conditions:
          - alias: If changed thermostat is Floor 2
            condition: template
            value_template: "{{ reference_entity_id == 'climate.hvac_floor_2' }}"
          - alias: And heat setpoint is too high
            condition: template
            value_template: "{{ target_setpoint < min_cool_setpoint }}"
          - condition: state
            entity_id: climate.hvac_floor_2
            state: cool
        sequence:
          - service: climate.set_temperature
            metadata: {}
            data:
              temperature: 19.44
            target:
              entity_id: climate.hvac_floor_2
mode: single
