alias: HVAC mode enforcement
description: Sync all HVAC thermostats to the same mode
trigger:
  - platform: state
    entity_id:
      - climate.hvac_floor_0
      - climate.hvac_floor_1
      - climate.hvac_floor_2
    from: null
    to: null
    for:
      hours: 0
      minutes: 0
      seconds: 2
condition: []
action:
  - alias: Sync modes
    if: []
    then:
      - service: climate.set_hvac_mode
        metadata: {}
        data:
          hvac_mode: "{{trigger.to_state.state}}"
        target:
          entity_id:
            - climate.hvac_floor_0
            - climate.hvac_floor_1
            - climate.hvac_floor_2
mode: single
