alias: HVAC mode enforcement
description: Sync all HVAC thermostats to the same mode
trigger:
  - platform: state
    entity_id:
      - climate.hvac_floor_0
      - climate.hvac_floor_1
      - climate.hvac_floor_2
    from: null
    to: null
    for:
      hours: 0
      minutes: 0
      seconds: 2
condition: []
action:
  - alias: Sync modes
    if: []
    then:
      - service: climate.set_hvac_mode
        metadata: {}
        data:
          hvac_mode: "{{trigger.to_state.state}}"
        target:
          device_id:
            - f1dc2d8f3b96cdccadbebe15c77dc355
            - 9c92936d39ac8e24b40a456aace0fc8c
            - 430d66ac3f25696332917ea915936d56
          entity_id:
            - climate.hvac_floor_0
            - climate.hvac_floor_1
            - climate.hvac_floor_2
mode: single
